# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.5.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.5.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/abduld/gputeachingkit-labs-develop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/abduld/gputeachingkit-labs-develop/libwb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.5.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.5.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/abduld/gputeachingkit-labs-develop/libwb/CMakeFiles /Users/abduld/gputeachingkit-labs-develop/libwb/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/abduld/gputeachingkit-labs-develop/libwb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named VectorAdd_Stream_Solution

# Build rule for target.
VectorAdd_Stream_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VectorAdd_Stream_Solution
.PHONY : VectorAdd_Stream_Solution

# fast build rule for target.
VectorAdd_Stream_Solution/fast:
	$(MAKE) -f CMakeFiles/VectorAdd_Stream_Solution.dir/build.make CMakeFiles/VectorAdd_Stream_Solution.dir/build
.PHONY : VectorAdd_Stream_Solution/fast

#=============================================================================
# Target rules for targets named ListScan_DatasetGenerator

# Build rule for target.
ListScan_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ListScan_DatasetGenerator
.PHONY : ListScan_DatasetGenerator

# fast build rule for target.
ListScan_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/ListScan_DatasetGenerator.dir/build.make CMakeFiles/ListScan_DatasetGenerator.dir/build
.PHONY : ListScan_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named VectorAdd_Stream_DatasetGenerator

# Build rule for target.
VectorAdd_Stream_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VectorAdd_Stream_DatasetGenerator
.PHONY : VectorAdd_Stream_DatasetGenerator

# fast build rule for target.
VectorAdd_Stream_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/VectorAdd_Stream_DatasetGenerator.dir/build.make CMakeFiles/VectorAdd_Stream_DatasetGenerator.dir/build
.PHONY : VectorAdd_Stream_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named ListScan_Solution

# Build rule for target.
ListScan_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ListScan_Solution
.PHONY : ListScan_Solution

# fast build rule for target.
ListScan_Solution/fast:
	$(MAKE) -f CMakeFiles/ListScan_Solution.dir/build.make CMakeFiles/ListScan_Solution.dir/build
.PHONY : ListScan_Solution/fast

#=============================================================================
# Target rules for targets named Reduction_Solution

# Build rule for target.
Reduction_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Reduction_Solution
.PHONY : Reduction_Solution

# fast build rule for target.
Reduction_Solution/fast:
	$(MAKE) -f CMakeFiles/Reduction_Solution.dir/build.make CMakeFiles/Reduction_Solution.dir/build
.PHONY : Reduction_Solution/fast

#=============================================================================
# Target rules for targets named ThrustReduction_DatasetGenerator

# Build rule for target.
ThrustReduction_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ThrustReduction_DatasetGenerator
.PHONY : ThrustReduction_DatasetGenerator

# fast build rule for target.
ThrustReduction_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/ThrustReduction_DatasetGenerator.dir/build.make CMakeFiles/ThrustReduction_DatasetGenerator.dir/build
.PHONY : ThrustReduction_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named ThrustReduction_Solution

# Build rule for target.
ThrustReduction_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ThrustReduction_Solution
.PHONY : ThrustReduction_Solution

# fast build rule for target.
ThrustReduction_Solution/fast:
	$(MAKE) -f CMakeFiles/ThrustReduction_Solution.dir/build.make CMakeFiles/ThrustReduction_Solution.dir/build
.PHONY : ThrustReduction_Solution/fast

#=============================================================================
# Target rules for targets named Stencil_DatasetGenerator

# Build rule for target.
Stencil_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Stencil_DatasetGenerator
.PHONY : Stencil_DatasetGenerator

# fast build rule for target.
Stencil_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/Stencil_DatasetGenerator.dir/build.make CMakeFiles/Stencil_DatasetGenerator.dir/build
.PHONY : Stencil_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named Convolution_Solution

# Build rule for target.
Convolution_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Convolution_Solution
.PHONY : Convolution_Solution

# fast build rule for target.
Convolution_Solution/fast:
	$(MAKE) -f CMakeFiles/Convolution_Solution.dir/build.make CMakeFiles/Convolution_Solution.dir/build
.PHONY : Convolution_Solution/fast

#=============================================================================
# Target rules for targets named ThrustListScan_DatasetGenerator

# Build rule for target.
ThrustListScan_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ThrustListScan_DatasetGenerator
.PHONY : ThrustListScan_DatasetGenerator

# fast build rule for target.
ThrustListScan_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/ThrustListScan_DatasetGenerator.dir/build.make CMakeFiles/ThrustListScan_DatasetGenerator.dir/build
.PHONY : ThrustListScan_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named Convolution_DatasetGenerator

# Build rule for target.
Convolution_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Convolution_DatasetGenerator
.PHONY : Convolution_DatasetGenerator

# fast build rule for target.
Convolution_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/Convolution_DatasetGenerator.dir/build.make CMakeFiles/Convolution_DatasetGenerator.dir/build
.PHONY : Convolution_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named VectorAdd_Solution

# Build rule for target.
VectorAdd_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VectorAdd_Solution
.PHONY : VectorAdd_Solution

# fast build rule for target.
VectorAdd_Solution/fast:
	$(MAKE) -f CMakeFiles/VectorAdd_Solution.dir/build.make CMakeFiles/VectorAdd_Solution.dir/build
.PHONY : VectorAdd_Solution/fast

#=============================================================================
# Target rules for targets named TextHistogram_DatasetGenerator

# Build rule for target.
TextHistogram_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TextHistogram_DatasetGenerator
.PHONY : TextHistogram_DatasetGenerator

# fast build rule for target.
TextHistogram_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/TextHistogram_DatasetGenerator.dir/build.make CMakeFiles/TextHistogram_DatasetGenerator.dir/build
.PHONY : TextHistogram_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named TextHistogram_Solution

# Build rule for target.
TextHistogram_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TextHistogram_Solution
.PHONY : TextHistogram_Solution

# fast build rule for target.
TextHistogram_Solution/fast:
	$(MAKE) -f CMakeFiles/TextHistogram_Solution.dir/build.make CMakeFiles/TextHistogram_Solution.dir/build
.PHONY : TextHistogram_Solution/fast

#=============================================================================
# Target rules for targets named ImageColorToGrayscale_Solution

# Build rule for target.
ImageColorToGrayscale_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImageColorToGrayscale_Solution
.PHONY : ImageColorToGrayscale_Solution

# fast build rule for target.
ImageColorToGrayscale_Solution/fast:
	$(MAKE) -f CMakeFiles/ImageColorToGrayscale_Solution.dir/build.make CMakeFiles/ImageColorToGrayscale_Solution.dir/build
.PHONY : ImageColorToGrayscale_Solution/fast

#=============================================================================
# Target rules for targets named TiledMatrixMultiplication_DatasetGenerator

# Build rule for target.
TiledMatrixMultiplication_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TiledMatrixMultiplication_DatasetGenerator
.PHONY : TiledMatrixMultiplication_DatasetGenerator

# fast build rule for target.
TiledMatrixMultiplication_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/TiledMatrixMultiplication_DatasetGenerator.dir/build.make CMakeFiles/TiledMatrixMultiplication_DatasetGenerator.dir/build
.PHONY : TiledMatrixMultiplication_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named TiledMatrixMultiplication_Solution

# Build rule for target.
TiledMatrixMultiplication_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TiledMatrixMultiplication_Solution
.PHONY : TiledMatrixMultiplication_Solution

# fast build rule for target.
TiledMatrixMultiplication_Solution/fast:
	$(MAKE) -f CMakeFiles/TiledMatrixMultiplication_Solution.dir/build.make CMakeFiles/TiledMatrixMultiplication_Solution.dir/build
.PHONY : TiledMatrixMultiplication_Solution/fast

#=============================================================================
# Target rules for targets named BasicMatrixMultiplication_DatasetGenerator

# Build rule for target.
BasicMatrixMultiplication_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BasicMatrixMultiplication_DatasetGenerator
.PHONY : BasicMatrixMultiplication_DatasetGenerator

# fast build rule for target.
BasicMatrixMultiplication_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/BasicMatrixMultiplication_DatasetGenerator.dir/build.make CMakeFiles/BasicMatrixMultiplication_DatasetGenerator.dir/build
.PHONY : BasicMatrixMultiplication_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named BasicMatrixMultiplication_Solution

# Build rule for target.
BasicMatrixMultiplication_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BasicMatrixMultiplication_Solution
.PHONY : BasicMatrixMultiplication_Solution

# fast build rule for target.
BasicMatrixMultiplication_Solution/fast:
	$(MAKE) -f CMakeFiles/BasicMatrixMultiplication_Solution.dir/build.make CMakeFiles/BasicMatrixMultiplication_Solution.dir/build
.PHONY : BasicMatrixMultiplication_Solution/fast

#=============================================================================
# Target rules for targets named ImageBlur_Solution

# Build rule for target.
ImageBlur_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImageBlur_Solution
.PHONY : ImageBlur_Solution

# fast build rule for target.
ImageBlur_Solution/fast:
	$(MAKE) -f CMakeFiles/ImageBlur_Solution.dir/build.make CMakeFiles/ImageBlur_Solution.dir/build
.PHONY : ImageBlur_Solution/fast

#=============================================================================
# Target rules for targets named Histogram_Solution

# Build rule for target.
Histogram_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Histogram_Solution
.PHONY : Histogram_Solution

# fast build rule for target.
Histogram_Solution/fast:
	$(MAKE) -f CMakeFiles/Histogram_Solution.dir/build.make CMakeFiles/Histogram_Solution.dir/build
.PHONY : Histogram_Solution/fast

#=============================================================================
# Target rules for targets named ThrustVectorAdd_DatasetGenerator

# Build rule for target.
ThrustVectorAdd_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ThrustVectorAdd_DatasetGenerator
.PHONY : ThrustVectorAdd_DatasetGenerator

# fast build rule for target.
ThrustVectorAdd_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/ThrustVectorAdd_DatasetGenerator.dir/build.make CMakeFiles/ThrustVectorAdd_DatasetGenerator.dir/build
.PHONY : ThrustVectorAdd_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named ThrustVectorAdd_Solution

# Build rule for target.
ThrustVectorAdd_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ThrustVectorAdd_Solution
.PHONY : ThrustVectorAdd_Solution

# fast build rule for target.
ThrustVectorAdd_Solution/fast:
	$(MAKE) -f CMakeFiles/ThrustVectorAdd_Solution.dir/build.make CMakeFiles/ThrustVectorAdd_Solution.dir/build
.PHONY : ThrustVectorAdd_Solution/fast

#=============================================================================
# Target rules for targets named ImageColorToGrayscale_DatasetGenerator

# Build rule for target.
ImageColorToGrayscale_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImageColorToGrayscale_DatasetGenerator
.PHONY : ImageColorToGrayscale_DatasetGenerator

# fast build rule for target.
ImageColorToGrayscale_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/ImageColorToGrayscale_DatasetGenerator.dir/build.make CMakeFiles/ImageColorToGrayscale_DatasetGenerator.dir/build
.PHONY : ImageColorToGrayscale_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named DeviceQuery_Solution

# Build rule for target.
DeviceQuery_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DeviceQuery_Solution
.PHONY : DeviceQuery_Solution

# fast build rule for target.
DeviceQuery_Solution/fast:
	$(MAKE) -f CMakeFiles/DeviceQuery_Solution.dir/build.make CMakeFiles/DeviceQuery_Solution.dir/build
.PHONY : DeviceQuery_Solution/fast

#=============================================================================
# Target rules for targets named Stencil_Solution

# Build rule for target.
Stencil_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Stencil_Solution
.PHONY : Stencil_Solution

# fast build rule for target.
Stencil_Solution/fast:
	$(MAKE) -f CMakeFiles/Stencil_Solution.dir/build.make CMakeFiles/Stencil_Solution.dir/build
.PHONY : Stencil_Solution/fast

#=============================================================================
# Target rules for targets named Histogram_DatasetGenerator

# Build rule for target.
Histogram_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Histogram_DatasetGenerator
.PHONY : Histogram_DatasetGenerator

# fast build rule for target.
Histogram_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/Histogram_DatasetGenerator.dir/build.make CMakeFiles/Histogram_DatasetGenerator.dir/build
.PHONY : Histogram_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named ImageBlur_DatasetGenerator

# Build rule for target.
ImageBlur_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImageBlur_DatasetGenerator
.PHONY : ImageBlur_DatasetGenerator

# fast build rule for target.
ImageBlur_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/ImageBlur_DatasetGenerator.dir/build.make CMakeFiles/ImageBlur_DatasetGenerator.dir/build
.PHONY : ImageBlur_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named ThrustListScan_Solution

# Build rule for target.
ThrustListScan_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ThrustListScan_Solution
.PHONY : ThrustListScan_Solution

# fast build rule for target.
ThrustListScan_Solution/fast:
	$(MAKE) -f CMakeFiles/ThrustListScan_Solution.dir/build.make CMakeFiles/ThrustListScan_Solution.dir/build
.PHONY : ThrustListScan_Solution/fast

#=============================================================================
# Target rules for targets named ThrustHistogramSort_DatasetGenerator

# Build rule for target.
ThrustHistogramSort_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ThrustHistogramSort_DatasetGenerator
.PHONY : ThrustHistogramSort_DatasetGenerator

# fast build rule for target.
ThrustHistogramSort_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/ThrustHistogramSort_DatasetGenerator.dir/build.make CMakeFiles/ThrustHistogramSort_DatasetGenerator.dir/build
.PHONY : ThrustHistogramSort_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named VectorAdd_DatasetGenerator

# Build rule for target.
VectorAdd_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VectorAdd_DatasetGenerator
.PHONY : VectorAdd_DatasetGenerator

# fast build rule for target.
VectorAdd_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/VectorAdd_DatasetGenerator.dir/build.make CMakeFiles/VectorAdd_DatasetGenerator.dir/build
.PHONY : VectorAdd_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named Reduction_DatasetGenerator

# Build rule for target.
Reduction_DatasetGenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Reduction_DatasetGenerator
.PHONY : Reduction_DatasetGenerator

# fast build rule for target.
Reduction_DatasetGenerator/fast:
	$(MAKE) -f CMakeFiles/Reduction_DatasetGenerator.dir/build.make CMakeFiles/Reduction_DatasetGenerator.dir/build
.PHONY : Reduction_DatasetGenerator/fast

#=============================================================================
# Target rules for targets named ThrustHistogramSort_Solution

# Build rule for target.
ThrustHistogramSort_Solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ThrustHistogramSort_Solution
.PHONY : ThrustHistogramSort_Solution

# fast build rule for target.
ThrustHistogramSort_Solution/fast:
	$(MAKE) -f CMakeFiles/ThrustHistogramSort_Solution.dir/build.make CMakeFiles/ThrustHistogramSort_Solution.dir/build
.PHONY : ThrustHistogramSort_Solution/fast

#=============================================================================
# Target rules for targets named wb

# Build rule for target.
wb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wb
.PHONY : wb

# fast build rule for target.
wb/fast:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/build
.PHONY : wb/fast

Module10/ListScan/dataset_generator.o: Module10/ListScan/dataset_generator.cpp.o

.PHONY : Module10/ListScan/dataset_generator.o

# target to build an object file
Module10/ListScan/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/ListScan_DatasetGenerator.dir/build.make CMakeFiles/ListScan_DatasetGenerator.dir/Module10/ListScan/dataset_generator.cpp.o
.PHONY : Module10/ListScan/dataset_generator.cpp.o

Module10/ListScan/dataset_generator.i: Module10/ListScan/dataset_generator.cpp.i

.PHONY : Module10/ListScan/dataset_generator.i

# target to preprocess a source file
Module10/ListScan/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/ListScan_DatasetGenerator.dir/build.make CMakeFiles/ListScan_DatasetGenerator.dir/Module10/ListScan/dataset_generator.cpp.i
.PHONY : Module10/ListScan/dataset_generator.cpp.i

Module10/ListScan/dataset_generator.s: Module10/ListScan/dataset_generator.cpp.s

.PHONY : Module10/ListScan/dataset_generator.s

# target to generate assembly for a file
Module10/ListScan/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/ListScan_DatasetGenerator.dir/build.make CMakeFiles/ListScan_DatasetGenerator.dir/Module10/ListScan/dataset_generator.cpp.s
.PHONY : Module10/ListScan/dataset_generator.cpp.s

Module10/ThrustListScan/dataset_generator.o: Module10/ThrustListScan/dataset_generator.cpp.o

.PHONY : Module10/ThrustListScan/dataset_generator.o

# target to build an object file
Module10/ThrustListScan/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/ThrustListScan_DatasetGenerator.dir/build.make CMakeFiles/ThrustListScan_DatasetGenerator.dir/Module10/ThrustListScan/dataset_generator.cpp.o
.PHONY : Module10/ThrustListScan/dataset_generator.cpp.o

Module10/ThrustListScan/dataset_generator.i: Module10/ThrustListScan/dataset_generator.cpp.i

.PHONY : Module10/ThrustListScan/dataset_generator.i

# target to preprocess a source file
Module10/ThrustListScan/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/ThrustListScan_DatasetGenerator.dir/build.make CMakeFiles/ThrustListScan_DatasetGenerator.dir/Module10/ThrustListScan/dataset_generator.cpp.i
.PHONY : Module10/ThrustListScan/dataset_generator.cpp.i

Module10/ThrustListScan/dataset_generator.s: Module10/ThrustListScan/dataset_generator.cpp.s

.PHONY : Module10/ThrustListScan/dataset_generator.s

# target to generate assembly for a file
Module10/ThrustListScan/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/ThrustListScan_DatasetGenerator.dir/build.make CMakeFiles/ThrustListScan_DatasetGenerator.dir/Module10/ThrustListScan/dataset_generator.cpp.s
.PHONY : Module10/ThrustListScan/dataset_generator.cpp.s

Module14/VectorAddStream/dataset_generator.o: Module14/VectorAddStream/dataset_generator.cpp.o

.PHONY : Module14/VectorAddStream/dataset_generator.o

# target to build an object file
Module14/VectorAddStream/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/VectorAdd_Stream_DatasetGenerator.dir/build.make CMakeFiles/VectorAdd_Stream_DatasetGenerator.dir/Module14/VectorAddStream/dataset_generator.cpp.o
.PHONY : Module14/VectorAddStream/dataset_generator.cpp.o

Module14/VectorAddStream/dataset_generator.i: Module14/VectorAddStream/dataset_generator.cpp.i

.PHONY : Module14/VectorAddStream/dataset_generator.i

# target to preprocess a source file
Module14/VectorAddStream/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/VectorAdd_Stream_DatasetGenerator.dir/build.make CMakeFiles/VectorAdd_Stream_DatasetGenerator.dir/Module14/VectorAddStream/dataset_generator.cpp.i
.PHONY : Module14/VectorAddStream/dataset_generator.cpp.i

Module14/VectorAddStream/dataset_generator.s: Module14/VectorAddStream/dataset_generator.cpp.s

.PHONY : Module14/VectorAddStream/dataset_generator.s

# target to generate assembly for a file
Module14/VectorAddStream/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/VectorAdd_Stream_DatasetGenerator.dir/build.make CMakeFiles/VectorAdd_Stream_DatasetGenerator.dir/Module14/VectorAddStream/dataset_generator.cpp.s
.PHONY : Module14/VectorAddStream/dataset_generator.cpp.s

Module3/ImageBlur/dataset_generator.o: Module3/ImageBlur/dataset_generator.cpp.o

.PHONY : Module3/ImageBlur/dataset_generator.o

# target to build an object file
Module3/ImageBlur/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/ImageBlur_DatasetGenerator.dir/build.make CMakeFiles/ImageBlur_DatasetGenerator.dir/Module3/ImageBlur/dataset_generator.cpp.o
.PHONY : Module3/ImageBlur/dataset_generator.cpp.o

Module3/ImageBlur/dataset_generator.i: Module3/ImageBlur/dataset_generator.cpp.i

.PHONY : Module3/ImageBlur/dataset_generator.i

# target to preprocess a source file
Module3/ImageBlur/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/ImageBlur_DatasetGenerator.dir/build.make CMakeFiles/ImageBlur_DatasetGenerator.dir/Module3/ImageBlur/dataset_generator.cpp.i
.PHONY : Module3/ImageBlur/dataset_generator.cpp.i

Module3/ImageBlur/dataset_generator.s: Module3/ImageBlur/dataset_generator.cpp.s

.PHONY : Module3/ImageBlur/dataset_generator.s

# target to generate assembly for a file
Module3/ImageBlur/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/ImageBlur_DatasetGenerator.dir/build.make CMakeFiles/ImageBlur_DatasetGenerator.dir/Module3/ImageBlur/dataset_generator.cpp.s
.PHONY : Module3/ImageBlur/dataset_generator.cpp.s

Module3/ImageColorToGrayscale/dataset_generator.o: Module3/ImageColorToGrayscale/dataset_generator.cpp.o

.PHONY : Module3/ImageColorToGrayscale/dataset_generator.o

# target to build an object file
Module3/ImageColorToGrayscale/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/ImageColorToGrayscale_DatasetGenerator.dir/build.make CMakeFiles/ImageColorToGrayscale_DatasetGenerator.dir/Module3/ImageColorToGrayscale/dataset_generator.cpp.o
.PHONY : Module3/ImageColorToGrayscale/dataset_generator.cpp.o

Module3/ImageColorToGrayscale/dataset_generator.i: Module3/ImageColorToGrayscale/dataset_generator.cpp.i

.PHONY : Module3/ImageColorToGrayscale/dataset_generator.i

# target to preprocess a source file
Module3/ImageColorToGrayscale/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/ImageColorToGrayscale_DatasetGenerator.dir/build.make CMakeFiles/ImageColorToGrayscale_DatasetGenerator.dir/Module3/ImageColorToGrayscale/dataset_generator.cpp.i
.PHONY : Module3/ImageColorToGrayscale/dataset_generator.cpp.i

Module3/ImageColorToGrayscale/dataset_generator.s: Module3/ImageColorToGrayscale/dataset_generator.cpp.s

.PHONY : Module3/ImageColorToGrayscale/dataset_generator.s

# target to generate assembly for a file
Module3/ImageColorToGrayscale/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/ImageColorToGrayscale_DatasetGenerator.dir/build.make CMakeFiles/ImageColorToGrayscale_DatasetGenerator.dir/Module3/ImageColorToGrayscale/dataset_generator.cpp.s
.PHONY : Module3/ImageColorToGrayscale/dataset_generator.cpp.s

Module3/ThrustVectorAdd/dataset_generator.o: Module3/ThrustVectorAdd/dataset_generator.cpp.o

.PHONY : Module3/ThrustVectorAdd/dataset_generator.o

# target to build an object file
Module3/ThrustVectorAdd/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/ThrustVectorAdd_DatasetGenerator.dir/build.make CMakeFiles/ThrustVectorAdd_DatasetGenerator.dir/Module3/ThrustVectorAdd/dataset_generator.cpp.o
.PHONY : Module3/ThrustVectorAdd/dataset_generator.cpp.o

Module3/ThrustVectorAdd/dataset_generator.i: Module3/ThrustVectorAdd/dataset_generator.cpp.i

.PHONY : Module3/ThrustVectorAdd/dataset_generator.i

# target to preprocess a source file
Module3/ThrustVectorAdd/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/ThrustVectorAdd_DatasetGenerator.dir/build.make CMakeFiles/ThrustVectorAdd_DatasetGenerator.dir/Module3/ThrustVectorAdd/dataset_generator.cpp.i
.PHONY : Module3/ThrustVectorAdd/dataset_generator.cpp.i

Module3/ThrustVectorAdd/dataset_generator.s: Module3/ThrustVectorAdd/dataset_generator.cpp.s

.PHONY : Module3/ThrustVectorAdd/dataset_generator.s

# target to generate assembly for a file
Module3/ThrustVectorAdd/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/ThrustVectorAdd_DatasetGenerator.dir/build.make CMakeFiles/ThrustVectorAdd_DatasetGenerator.dir/Module3/ThrustVectorAdd/dataset_generator.cpp.s
.PHONY : Module3/ThrustVectorAdd/dataset_generator.cpp.s

Module3/VectorAdd/dataset_generator.o: Module3/VectorAdd/dataset_generator.cpp.o

.PHONY : Module3/VectorAdd/dataset_generator.o

# target to build an object file
Module3/VectorAdd/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/VectorAdd_DatasetGenerator.dir/build.make CMakeFiles/VectorAdd_DatasetGenerator.dir/Module3/VectorAdd/dataset_generator.cpp.o
.PHONY : Module3/VectorAdd/dataset_generator.cpp.o

Module3/VectorAdd/dataset_generator.i: Module3/VectorAdd/dataset_generator.cpp.i

.PHONY : Module3/VectorAdd/dataset_generator.i

# target to preprocess a source file
Module3/VectorAdd/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/VectorAdd_DatasetGenerator.dir/build.make CMakeFiles/VectorAdd_DatasetGenerator.dir/Module3/VectorAdd/dataset_generator.cpp.i
.PHONY : Module3/VectorAdd/dataset_generator.cpp.i

Module3/VectorAdd/dataset_generator.s: Module3/VectorAdd/dataset_generator.cpp.s

.PHONY : Module3/VectorAdd/dataset_generator.s

# target to generate assembly for a file
Module3/VectorAdd/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/VectorAdd_DatasetGenerator.dir/build.make CMakeFiles/VectorAdd_DatasetGenerator.dir/Module3/VectorAdd/dataset_generator.cpp.s
.PHONY : Module3/VectorAdd/dataset_generator.cpp.s

Module4/BasicMatrixMultiplication/dataset_generator.o: Module4/BasicMatrixMultiplication/dataset_generator.cpp.o

.PHONY : Module4/BasicMatrixMultiplication/dataset_generator.o

# target to build an object file
Module4/BasicMatrixMultiplication/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/BasicMatrixMultiplication_DatasetGenerator.dir/build.make CMakeFiles/BasicMatrixMultiplication_DatasetGenerator.dir/Module4/BasicMatrixMultiplication/dataset_generator.cpp.o
.PHONY : Module4/BasicMatrixMultiplication/dataset_generator.cpp.o

Module4/BasicMatrixMultiplication/dataset_generator.i: Module4/BasicMatrixMultiplication/dataset_generator.cpp.i

.PHONY : Module4/BasicMatrixMultiplication/dataset_generator.i

# target to preprocess a source file
Module4/BasicMatrixMultiplication/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/BasicMatrixMultiplication_DatasetGenerator.dir/build.make CMakeFiles/BasicMatrixMultiplication_DatasetGenerator.dir/Module4/BasicMatrixMultiplication/dataset_generator.cpp.i
.PHONY : Module4/BasicMatrixMultiplication/dataset_generator.cpp.i

Module4/BasicMatrixMultiplication/dataset_generator.s: Module4/BasicMatrixMultiplication/dataset_generator.cpp.s

.PHONY : Module4/BasicMatrixMultiplication/dataset_generator.s

# target to generate assembly for a file
Module4/BasicMatrixMultiplication/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/BasicMatrixMultiplication_DatasetGenerator.dir/build.make CMakeFiles/BasicMatrixMultiplication_DatasetGenerator.dir/Module4/BasicMatrixMultiplication/dataset_generator.cpp.s
.PHONY : Module4/BasicMatrixMultiplication/dataset_generator.cpp.s

Module4/TiledMatrixMultiplication/dataset_generator.o: Module4/TiledMatrixMultiplication/dataset_generator.cpp.o

.PHONY : Module4/TiledMatrixMultiplication/dataset_generator.o

# target to build an object file
Module4/TiledMatrixMultiplication/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/TiledMatrixMultiplication_DatasetGenerator.dir/build.make CMakeFiles/TiledMatrixMultiplication_DatasetGenerator.dir/Module4/TiledMatrixMultiplication/dataset_generator.cpp.o
.PHONY : Module4/TiledMatrixMultiplication/dataset_generator.cpp.o

Module4/TiledMatrixMultiplication/dataset_generator.i: Module4/TiledMatrixMultiplication/dataset_generator.cpp.i

.PHONY : Module4/TiledMatrixMultiplication/dataset_generator.i

# target to preprocess a source file
Module4/TiledMatrixMultiplication/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/TiledMatrixMultiplication_DatasetGenerator.dir/build.make CMakeFiles/TiledMatrixMultiplication_DatasetGenerator.dir/Module4/TiledMatrixMultiplication/dataset_generator.cpp.i
.PHONY : Module4/TiledMatrixMultiplication/dataset_generator.cpp.i

Module4/TiledMatrixMultiplication/dataset_generator.s: Module4/TiledMatrixMultiplication/dataset_generator.cpp.s

.PHONY : Module4/TiledMatrixMultiplication/dataset_generator.s

# target to generate assembly for a file
Module4/TiledMatrixMultiplication/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/TiledMatrixMultiplication_DatasetGenerator.dir/build.make CMakeFiles/TiledMatrixMultiplication_DatasetGenerator.dir/Module4/TiledMatrixMultiplication/dataset_generator.cpp.s
.PHONY : Module4/TiledMatrixMultiplication/dataset_generator.cpp.s

Module7/Histogram/dataset_generator.o: Module7/Histogram/dataset_generator.cpp.o

.PHONY : Module7/Histogram/dataset_generator.o

# target to build an object file
Module7/Histogram/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/Histogram_DatasetGenerator.dir/build.make CMakeFiles/Histogram_DatasetGenerator.dir/Module7/Histogram/dataset_generator.cpp.o
.PHONY : Module7/Histogram/dataset_generator.cpp.o

Module7/Histogram/dataset_generator.i: Module7/Histogram/dataset_generator.cpp.i

.PHONY : Module7/Histogram/dataset_generator.i

# target to preprocess a source file
Module7/Histogram/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/Histogram_DatasetGenerator.dir/build.make CMakeFiles/Histogram_DatasetGenerator.dir/Module7/Histogram/dataset_generator.cpp.i
.PHONY : Module7/Histogram/dataset_generator.cpp.i

Module7/Histogram/dataset_generator.s: Module7/Histogram/dataset_generator.cpp.s

.PHONY : Module7/Histogram/dataset_generator.s

# target to generate assembly for a file
Module7/Histogram/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/Histogram_DatasetGenerator.dir/build.make CMakeFiles/Histogram_DatasetGenerator.dir/Module7/Histogram/dataset_generator.cpp.s
.PHONY : Module7/Histogram/dataset_generator.cpp.s

Module7/TextHistogram/dataset_generator.o: Module7/TextHistogram/dataset_generator.cpp.o

.PHONY : Module7/TextHistogram/dataset_generator.o

# target to build an object file
Module7/TextHistogram/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/TextHistogram_DatasetGenerator.dir/build.make CMakeFiles/TextHistogram_DatasetGenerator.dir/Module7/TextHistogram/dataset_generator.cpp.o
.PHONY : Module7/TextHistogram/dataset_generator.cpp.o

Module7/TextHistogram/dataset_generator.i: Module7/TextHistogram/dataset_generator.cpp.i

.PHONY : Module7/TextHistogram/dataset_generator.i

# target to preprocess a source file
Module7/TextHistogram/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/TextHistogram_DatasetGenerator.dir/build.make CMakeFiles/TextHistogram_DatasetGenerator.dir/Module7/TextHistogram/dataset_generator.cpp.i
.PHONY : Module7/TextHistogram/dataset_generator.cpp.i

Module7/TextHistogram/dataset_generator.s: Module7/TextHistogram/dataset_generator.cpp.s

.PHONY : Module7/TextHistogram/dataset_generator.s

# target to generate assembly for a file
Module7/TextHistogram/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/TextHistogram_DatasetGenerator.dir/build.make CMakeFiles/TextHistogram_DatasetGenerator.dir/Module7/TextHistogram/dataset_generator.cpp.s
.PHONY : Module7/TextHistogram/dataset_generator.cpp.s

Module7/ThrustHistogramSort/dataset_generator.o: Module7/ThrustHistogramSort/dataset_generator.cpp.o

.PHONY : Module7/ThrustHistogramSort/dataset_generator.o

# target to build an object file
Module7/ThrustHistogramSort/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/ThrustHistogramSort_DatasetGenerator.dir/build.make CMakeFiles/ThrustHistogramSort_DatasetGenerator.dir/Module7/ThrustHistogramSort/dataset_generator.cpp.o
.PHONY : Module7/ThrustHistogramSort/dataset_generator.cpp.o

Module7/ThrustHistogramSort/dataset_generator.i: Module7/ThrustHistogramSort/dataset_generator.cpp.i

.PHONY : Module7/ThrustHistogramSort/dataset_generator.i

# target to preprocess a source file
Module7/ThrustHistogramSort/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/ThrustHistogramSort_DatasetGenerator.dir/build.make CMakeFiles/ThrustHistogramSort_DatasetGenerator.dir/Module7/ThrustHistogramSort/dataset_generator.cpp.i
.PHONY : Module7/ThrustHistogramSort/dataset_generator.cpp.i

Module7/ThrustHistogramSort/dataset_generator.s: Module7/ThrustHistogramSort/dataset_generator.cpp.s

.PHONY : Module7/ThrustHistogramSort/dataset_generator.s

# target to generate assembly for a file
Module7/ThrustHistogramSort/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/ThrustHistogramSort_DatasetGenerator.dir/build.make CMakeFiles/ThrustHistogramSort_DatasetGenerator.dir/Module7/ThrustHistogramSort/dataset_generator.cpp.s
.PHONY : Module7/ThrustHistogramSort/dataset_generator.cpp.s

Module8/Convolution/dataset_generator.o: Module8/Convolution/dataset_generator.cpp.o

.PHONY : Module8/Convolution/dataset_generator.o

# target to build an object file
Module8/Convolution/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/Convolution_DatasetGenerator.dir/build.make CMakeFiles/Convolution_DatasetGenerator.dir/Module8/Convolution/dataset_generator.cpp.o
.PHONY : Module8/Convolution/dataset_generator.cpp.o

Module8/Convolution/dataset_generator.i: Module8/Convolution/dataset_generator.cpp.i

.PHONY : Module8/Convolution/dataset_generator.i

# target to preprocess a source file
Module8/Convolution/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/Convolution_DatasetGenerator.dir/build.make CMakeFiles/Convolution_DatasetGenerator.dir/Module8/Convolution/dataset_generator.cpp.i
.PHONY : Module8/Convolution/dataset_generator.cpp.i

Module8/Convolution/dataset_generator.s: Module8/Convolution/dataset_generator.cpp.s

.PHONY : Module8/Convolution/dataset_generator.s

# target to generate assembly for a file
Module8/Convolution/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/Convolution_DatasetGenerator.dir/build.make CMakeFiles/Convolution_DatasetGenerator.dir/Module8/Convolution/dataset_generator.cpp.s
.PHONY : Module8/Convolution/dataset_generator.cpp.s

Module8/Stencil/dataset_generator.o: Module8/Stencil/dataset_generator.cpp.o

.PHONY : Module8/Stencil/dataset_generator.o

# target to build an object file
Module8/Stencil/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/Stencil_DatasetGenerator.dir/build.make CMakeFiles/Stencil_DatasetGenerator.dir/Module8/Stencil/dataset_generator.cpp.o
.PHONY : Module8/Stencil/dataset_generator.cpp.o

Module8/Stencil/dataset_generator.i: Module8/Stencil/dataset_generator.cpp.i

.PHONY : Module8/Stencil/dataset_generator.i

# target to preprocess a source file
Module8/Stencil/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/Stencil_DatasetGenerator.dir/build.make CMakeFiles/Stencil_DatasetGenerator.dir/Module8/Stencil/dataset_generator.cpp.i
.PHONY : Module8/Stencil/dataset_generator.cpp.i

Module8/Stencil/dataset_generator.s: Module8/Stencil/dataset_generator.cpp.s

.PHONY : Module8/Stencil/dataset_generator.s

# target to generate assembly for a file
Module8/Stencil/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/Stencil_DatasetGenerator.dir/build.make CMakeFiles/Stencil_DatasetGenerator.dir/Module8/Stencil/dataset_generator.cpp.s
.PHONY : Module8/Stencil/dataset_generator.cpp.s

Module9/Reduction/dataset_generator.o: Module9/Reduction/dataset_generator.cpp.o

.PHONY : Module9/Reduction/dataset_generator.o

# target to build an object file
Module9/Reduction/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/Reduction_DatasetGenerator.dir/build.make CMakeFiles/Reduction_DatasetGenerator.dir/Module9/Reduction/dataset_generator.cpp.o
.PHONY : Module9/Reduction/dataset_generator.cpp.o

Module9/Reduction/dataset_generator.i: Module9/Reduction/dataset_generator.cpp.i

.PHONY : Module9/Reduction/dataset_generator.i

# target to preprocess a source file
Module9/Reduction/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/Reduction_DatasetGenerator.dir/build.make CMakeFiles/Reduction_DatasetGenerator.dir/Module9/Reduction/dataset_generator.cpp.i
.PHONY : Module9/Reduction/dataset_generator.cpp.i

Module9/Reduction/dataset_generator.s: Module9/Reduction/dataset_generator.cpp.s

.PHONY : Module9/Reduction/dataset_generator.s

# target to generate assembly for a file
Module9/Reduction/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/Reduction_DatasetGenerator.dir/build.make CMakeFiles/Reduction_DatasetGenerator.dir/Module9/Reduction/dataset_generator.cpp.s
.PHONY : Module9/Reduction/dataset_generator.cpp.s

Module9/ThrustReduction/dataset_generator.o: Module9/ThrustReduction/dataset_generator.cpp.o

.PHONY : Module9/ThrustReduction/dataset_generator.o

# target to build an object file
Module9/ThrustReduction/dataset_generator.cpp.o:
	$(MAKE) -f CMakeFiles/ThrustReduction_DatasetGenerator.dir/build.make CMakeFiles/ThrustReduction_DatasetGenerator.dir/Module9/ThrustReduction/dataset_generator.cpp.o
.PHONY : Module9/ThrustReduction/dataset_generator.cpp.o

Module9/ThrustReduction/dataset_generator.i: Module9/ThrustReduction/dataset_generator.cpp.i

.PHONY : Module9/ThrustReduction/dataset_generator.i

# target to preprocess a source file
Module9/ThrustReduction/dataset_generator.cpp.i:
	$(MAKE) -f CMakeFiles/ThrustReduction_DatasetGenerator.dir/build.make CMakeFiles/ThrustReduction_DatasetGenerator.dir/Module9/ThrustReduction/dataset_generator.cpp.i
.PHONY : Module9/ThrustReduction/dataset_generator.cpp.i

Module9/ThrustReduction/dataset_generator.s: Module9/ThrustReduction/dataset_generator.cpp.s

.PHONY : Module9/ThrustReduction/dataset_generator.s

# target to generate assembly for a file
Module9/ThrustReduction/dataset_generator.cpp.s:
	$(MAKE) -f CMakeFiles/ThrustReduction_DatasetGenerator.dir/build.make CMakeFiles/ThrustReduction_DatasetGenerator.dir/Module9/ThrustReduction/dataset_generator.cpp.s
.PHONY : Module9/ThrustReduction/dataset_generator.cpp.s

vendor/json11.o: vendor/json11.cpp.o

.PHONY : vendor/json11.o

# target to build an object file
vendor/json11.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/vendor/json11.cpp.o
.PHONY : vendor/json11.cpp.o

vendor/json11.i: vendor/json11.cpp.i

.PHONY : vendor/json11.i

# target to preprocess a source file
vendor/json11.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/vendor/json11.cpp.i
.PHONY : vendor/json11.cpp.i

vendor/json11.s: vendor/json11.cpp.s

.PHONY : vendor/json11.s

# target to generate assembly for a file
vendor/json11.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/vendor/json11.cpp.s
.PHONY : vendor/json11.cpp.s

wbArg.o: wbArg.cpp.o

.PHONY : wbArg.o

# target to build an object file
wbArg.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbArg.cpp.o
.PHONY : wbArg.cpp.o

wbArg.i: wbArg.cpp.i

.PHONY : wbArg.i

# target to preprocess a source file
wbArg.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbArg.cpp.i
.PHONY : wbArg.cpp.i

wbArg.s: wbArg.cpp.s

.PHONY : wbArg.s

# target to generate assembly for a file
wbArg.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbArg.cpp.s
.PHONY : wbArg.cpp.s

wbCUDA.o: wbCUDA.cpp.o

.PHONY : wbCUDA.o

# target to build an object file
wbCUDA.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbCUDA.cpp.o
.PHONY : wbCUDA.cpp.o

wbCUDA.i: wbCUDA.cpp.i

.PHONY : wbCUDA.i

# target to preprocess a source file
wbCUDA.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbCUDA.cpp.i
.PHONY : wbCUDA.cpp.i

wbCUDA.s: wbCUDA.cpp.s

.PHONY : wbCUDA.s

# target to generate assembly for a file
wbCUDA.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbCUDA.cpp.s
.PHONY : wbCUDA.cpp.s

wbDataset.o: wbDataset.cpp.o

.PHONY : wbDataset.o

# target to build an object file
wbDataset.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbDataset.cpp.o
.PHONY : wbDataset.cpp.o

wbDataset.i: wbDataset.cpp.i

.PHONY : wbDataset.i

# target to preprocess a source file
wbDataset.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbDataset.cpp.i
.PHONY : wbDataset.cpp.i

wbDataset.s: wbDataset.cpp.s

.PHONY : wbDataset.s

# target to generate assembly for a file
wbDataset.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbDataset.cpp.s
.PHONY : wbDataset.cpp.s

wbDirectory.o: wbDirectory.cpp.o

.PHONY : wbDirectory.o

# target to build an object file
wbDirectory.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbDirectory.cpp.o
.PHONY : wbDirectory.cpp.o

wbDirectory.i: wbDirectory.cpp.i

.PHONY : wbDirectory.i

# target to preprocess a source file
wbDirectory.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbDirectory.cpp.i
.PHONY : wbDirectory.cpp.i

wbDirectory.s: wbDirectory.cpp.s

.PHONY : wbDirectory.s

# target to generate assembly for a file
wbDirectory.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbDirectory.cpp.s
.PHONY : wbDirectory.cpp.s

wbExit.o: wbExit.cpp.o

.PHONY : wbExit.o

# target to build an object file
wbExit.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbExit.cpp.o
.PHONY : wbExit.cpp.o

wbExit.i: wbExit.cpp.i

.PHONY : wbExit.i

# target to preprocess a source file
wbExit.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbExit.cpp.i
.PHONY : wbExit.cpp.i

wbExit.s: wbExit.cpp.s

.PHONY : wbExit.s

# target to generate assembly for a file
wbExit.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbExit.cpp.s
.PHONY : wbExit.cpp.s

wbExport.o: wbExport.cpp.o

.PHONY : wbExport.o

# target to build an object file
wbExport.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbExport.cpp.o
.PHONY : wbExport.cpp.o

wbExport.i: wbExport.cpp.i

.PHONY : wbExport.i

# target to preprocess a source file
wbExport.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbExport.cpp.i
.PHONY : wbExport.cpp.i

wbExport.s: wbExport.cpp.s

.PHONY : wbExport.s

# target to generate assembly for a file
wbExport.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbExport.cpp.s
.PHONY : wbExport.cpp.s

wbFile.o: wbFile.cpp.o

.PHONY : wbFile.o

# target to build an object file
wbFile.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbFile.cpp.o
.PHONY : wbFile.cpp.o

wbFile.i: wbFile.cpp.i

.PHONY : wbFile.i

# target to preprocess a source file
wbFile.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbFile.cpp.i
.PHONY : wbFile.cpp.i

wbFile.s: wbFile.cpp.s

.PHONY : wbFile.s

# target to generate assembly for a file
wbFile.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbFile.cpp.s
.PHONY : wbFile.cpp.s

wbImage.o: wbImage.cpp.o

.PHONY : wbImage.o

# target to build an object file
wbImage.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbImage.cpp.o
.PHONY : wbImage.cpp.o

wbImage.i: wbImage.cpp.i

.PHONY : wbImage.i

# target to preprocess a source file
wbImage.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbImage.cpp.i
.PHONY : wbImage.cpp.i

wbImage.s: wbImage.cpp.s

.PHONY : wbImage.s

# target to generate assembly for a file
wbImage.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbImage.cpp.s
.PHONY : wbImage.cpp.s

wbImport.o: wbImport.cpp.o

.PHONY : wbImport.o

# target to build an object file
wbImport.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbImport.cpp.o
.PHONY : wbImport.cpp.o

wbImport.i: wbImport.cpp.i

.PHONY : wbImport.i

# target to preprocess a source file
wbImport.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbImport.cpp.i
.PHONY : wbImport.cpp.i

wbImport.s: wbImport.cpp.s

.PHONY : wbImport.s

# target to generate assembly for a file
wbImport.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbImport.cpp.s
.PHONY : wbImport.cpp.s

wbInit.o: wbInit.cpp.o

.PHONY : wbInit.o

# target to build an object file
wbInit.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbInit.cpp.o
.PHONY : wbInit.cpp.o

wbInit.i: wbInit.cpp.i

.PHONY : wbInit.i

# target to preprocess a source file
wbInit.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbInit.cpp.i
.PHONY : wbInit.cpp.i

wbInit.s: wbInit.cpp.s

.PHONY : wbInit.s

# target to generate assembly for a file
wbInit.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbInit.cpp.s
.PHONY : wbInit.cpp.s

wbLogger.o: wbLogger.cpp.o

.PHONY : wbLogger.o

# target to build an object file
wbLogger.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbLogger.cpp.o
.PHONY : wbLogger.cpp.o

wbLogger.i: wbLogger.cpp.i

.PHONY : wbLogger.i

# target to preprocess a source file
wbLogger.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbLogger.cpp.i
.PHONY : wbLogger.cpp.i

wbLogger.s: wbLogger.cpp.s

.PHONY : wbLogger.s

# target to generate assembly for a file
wbLogger.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbLogger.cpp.s
.PHONY : wbLogger.cpp.s

wbMPI.o: wbMPI.cpp.o

.PHONY : wbMPI.o

# target to build an object file
wbMPI.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbMPI.cpp.o
.PHONY : wbMPI.cpp.o

wbMPI.i: wbMPI.cpp.i

.PHONY : wbMPI.i

# target to preprocess a source file
wbMPI.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbMPI.cpp.i
.PHONY : wbMPI.cpp.i

wbMPI.s: wbMPI.cpp.s

.PHONY : wbMPI.s

# target to generate assembly for a file
wbMPI.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbMPI.cpp.s
.PHONY : wbMPI.cpp.s

wbPPM.o: wbPPM.cpp.o

.PHONY : wbPPM.o

# target to build an object file
wbPPM.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbPPM.cpp.o
.PHONY : wbPPM.cpp.o

wbPPM.i: wbPPM.cpp.i

.PHONY : wbPPM.i

# target to preprocess a source file
wbPPM.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbPPM.cpp.i
.PHONY : wbPPM.cpp.i

wbPPM.s: wbPPM.cpp.s

.PHONY : wbPPM.s

# target to generate assembly for a file
wbPPM.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbPPM.cpp.s
.PHONY : wbPPM.cpp.s

wbPath.o: wbPath.cpp.o

.PHONY : wbPath.o

# target to build an object file
wbPath.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbPath.cpp.o
.PHONY : wbPath.cpp.o

wbPath.i: wbPath.cpp.i

.PHONY : wbPath.i

# target to preprocess a source file
wbPath.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbPath.cpp.i
.PHONY : wbPath.cpp.i

wbPath.s: wbPath.cpp.s

.PHONY : wbPath.s

# target to generate assembly for a file
wbPath.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbPath.cpp.s
.PHONY : wbPath.cpp.s

wbSolution.o: wbSolution.cpp.o

.PHONY : wbSolution.o

# target to build an object file
wbSolution.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbSolution.cpp.o
.PHONY : wbSolution.cpp.o

wbSolution.i: wbSolution.cpp.i

.PHONY : wbSolution.i

# target to preprocess a source file
wbSolution.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbSolution.cpp.i
.PHONY : wbSolution.cpp.i

wbSolution.s: wbSolution.cpp.s

.PHONY : wbSolution.s

# target to generate assembly for a file
wbSolution.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbSolution.cpp.s
.PHONY : wbSolution.cpp.s

wbSparse.o: wbSparse.cpp.o

.PHONY : wbSparse.o

# target to build an object file
wbSparse.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbSparse.cpp.o
.PHONY : wbSparse.cpp.o

wbSparse.i: wbSparse.cpp.i

.PHONY : wbSparse.i

# target to preprocess a source file
wbSparse.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbSparse.cpp.i
.PHONY : wbSparse.cpp.i

wbSparse.s: wbSparse.cpp.s

.PHONY : wbSparse.s

# target to generate assembly for a file
wbSparse.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbSparse.cpp.s
.PHONY : wbSparse.cpp.s

wbTimer.o: wbTimer.cpp.o

.PHONY : wbTimer.o

# target to build an object file
wbTimer.cpp.o:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbTimer.cpp.o
.PHONY : wbTimer.cpp.o

wbTimer.i: wbTimer.cpp.i

.PHONY : wbTimer.i

# target to preprocess a source file
wbTimer.cpp.i:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbTimer.cpp.i
.PHONY : wbTimer.cpp.i

wbTimer.s: wbTimer.cpp.s

.PHONY : wbTimer.s

# target to generate assembly for a file
wbTimer.cpp.s:
	$(MAKE) -f CMakeFiles/wb.dir/build.make CMakeFiles/wb.dir/wbTimer.cpp.s
.PHONY : wbTimer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... VectorAdd_Stream_Solution"
	@echo "... ListScan_DatasetGenerator"
	@echo "... VectorAdd_Stream_DatasetGenerator"
	@echo "... ListScan_Solution"
	@echo "... Reduction_Solution"
	@echo "... ThrustReduction_DatasetGenerator"
	@echo "... ThrustReduction_Solution"
	@echo "... Stencil_DatasetGenerator"
	@echo "... Convolution_Solution"
	@echo "... ThrustListScan_DatasetGenerator"
	@echo "... Convolution_DatasetGenerator"
	@echo "... VectorAdd_Solution"
	@echo "... TextHistogram_DatasetGenerator"
	@echo "... TextHistogram_Solution"
	@echo "... ImageColorToGrayscale_Solution"
	@echo "... TiledMatrixMultiplication_DatasetGenerator"
	@echo "... TiledMatrixMultiplication_Solution"
	@echo "... BasicMatrixMultiplication_DatasetGenerator"
	@echo "... BasicMatrixMultiplication_Solution"
	@echo "... ImageBlur_Solution"
	@echo "... Histogram_Solution"
	@echo "... ThrustVectorAdd_DatasetGenerator"
	@echo "... ThrustVectorAdd_Solution"
	@echo "... ImageColorToGrayscale_DatasetGenerator"
	@echo "... DeviceQuery_Solution"
	@echo "... Stencil_Solution"
	@echo "... Histogram_DatasetGenerator"
	@echo "... ImageBlur_DatasetGenerator"
	@echo "... ThrustListScan_Solution"
	@echo "... ThrustHistogramSort_DatasetGenerator"
	@echo "... VectorAdd_DatasetGenerator"
	@echo "... Reduction_DatasetGenerator"
	@echo "... ThrustHistogramSort_Solution"
	@echo "... wb"
	@echo "... Module10/ListScan/dataset_generator.o"
	@echo "... Module10/ListScan/dataset_generator.i"
	@echo "... Module10/ListScan/dataset_generator.s"
	@echo "... Module10/ThrustListScan/dataset_generator.o"
	@echo "... Module10/ThrustListScan/dataset_generator.i"
	@echo "... Module10/ThrustListScan/dataset_generator.s"
	@echo "... Module14/VectorAddStream/dataset_generator.o"
	@echo "... Module14/VectorAddStream/dataset_generator.i"
	@echo "... Module14/VectorAddStream/dataset_generator.s"
	@echo "... Module3/ImageBlur/dataset_generator.o"
	@echo "... Module3/ImageBlur/dataset_generator.i"
	@echo "... Module3/ImageBlur/dataset_generator.s"
	@echo "... Module3/ImageColorToGrayscale/dataset_generator.o"
	@echo "... Module3/ImageColorToGrayscale/dataset_generator.i"
	@echo "... Module3/ImageColorToGrayscale/dataset_generator.s"
	@echo "... Module3/ThrustVectorAdd/dataset_generator.o"
	@echo "... Module3/ThrustVectorAdd/dataset_generator.i"
	@echo "... Module3/ThrustVectorAdd/dataset_generator.s"
	@echo "... Module3/VectorAdd/dataset_generator.o"
	@echo "... Module3/VectorAdd/dataset_generator.i"
	@echo "... Module3/VectorAdd/dataset_generator.s"
	@echo "... Module4/BasicMatrixMultiplication/dataset_generator.o"
	@echo "... Module4/BasicMatrixMultiplication/dataset_generator.i"
	@echo "... Module4/BasicMatrixMultiplication/dataset_generator.s"
	@echo "... Module4/TiledMatrixMultiplication/dataset_generator.o"
	@echo "... Module4/TiledMatrixMultiplication/dataset_generator.i"
	@echo "... Module4/TiledMatrixMultiplication/dataset_generator.s"
	@echo "... Module7/Histogram/dataset_generator.o"
	@echo "... Module7/Histogram/dataset_generator.i"
	@echo "... Module7/Histogram/dataset_generator.s"
	@echo "... Module7/TextHistogram/dataset_generator.o"
	@echo "... Module7/TextHistogram/dataset_generator.i"
	@echo "... Module7/TextHistogram/dataset_generator.s"
	@echo "... Module7/ThrustHistogramSort/dataset_generator.o"
	@echo "... Module7/ThrustHistogramSort/dataset_generator.i"
	@echo "... Module7/ThrustHistogramSort/dataset_generator.s"
	@echo "... Module8/Convolution/dataset_generator.o"
	@echo "... Module8/Convolution/dataset_generator.i"
	@echo "... Module8/Convolution/dataset_generator.s"
	@echo "... Module8/Stencil/dataset_generator.o"
	@echo "... Module8/Stencil/dataset_generator.i"
	@echo "... Module8/Stencil/dataset_generator.s"
	@echo "... Module9/Reduction/dataset_generator.o"
	@echo "... Module9/Reduction/dataset_generator.i"
	@echo "... Module9/Reduction/dataset_generator.s"
	@echo "... Module9/ThrustReduction/dataset_generator.o"
	@echo "... Module9/ThrustReduction/dataset_generator.i"
	@echo "... Module9/ThrustReduction/dataset_generator.s"
	@echo "... vendor/json11.o"
	@echo "... vendor/json11.i"
	@echo "... vendor/json11.s"
	@echo "... wbArg.o"
	@echo "... wbArg.i"
	@echo "... wbArg.s"
	@echo "... wbCUDA.o"
	@echo "... wbCUDA.i"
	@echo "... wbCUDA.s"
	@echo "... wbDataset.o"
	@echo "... wbDataset.i"
	@echo "... wbDataset.s"
	@echo "... wbDirectory.o"
	@echo "... wbDirectory.i"
	@echo "... wbDirectory.s"
	@echo "... wbExit.o"
	@echo "... wbExit.i"
	@echo "... wbExit.s"
	@echo "... wbExport.o"
	@echo "... wbExport.i"
	@echo "... wbExport.s"
	@echo "... wbFile.o"
	@echo "... wbFile.i"
	@echo "... wbFile.s"
	@echo "... wbImage.o"
	@echo "... wbImage.i"
	@echo "... wbImage.s"
	@echo "... wbImport.o"
	@echo "... wbImport.i"
	@echo "... wbImport.s"
	@echo "... wbInit.o"
	@echo "... wbInit.i"
	@echo "... wbInit.s"
	@echo "... wbLogger.o"
	@echo "... wbLogger.i"
	@echo "... wbLogger.s"
	@echo "... wbMPI.o"
	@echo "... wbMPI.i"
	@echo "... wbMPI.s"
	@echo "... wbPPM.o"
	@echo "... wbPPM.i"
	@echo "... wbPPM.s"
	@echo "... wbPath.o"
	@echo "... wbPath.i"
	@echo "... wbPath.s"
	@echo "... wbSolution.o"
	@echo "... wbSolution.i"
	@echo "... wbSolution.s"
	@echo "... wbSparse.o"
	@echo "... wbSparse.i"
	@echo "... wbSparse.s"
	@echo "... wbTimer.o"
	@echo "... wbTimer.i"
	@echo "... wbTimer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

