
file(GLOB THESE_CPP_FILES
    ${CMAKE_CURRENT_LIST_DIR}/*.cpp
)

file(GLOB THESE_TEST_FILES
    ${CMAKE_CURRENT_LIST_DIR}/*_test.cpp
)

list(REMOVE_ITEM THESE_CPP_FILES ${THESE_TEST_FILES})

file(GLOB THESE_HEADER_FILES
    ${CMAKE_CURRENT_LIST_DIR}/*.h
)

list(APPEND LIBWB_HEADER_FILES
    ${THESE_HEADER_FILES}
)

list(APPEND LIBWB_SOURCE_FILES
    ${THESE_CPP_FILES}
    ${CMAKE_CURRENT_LIST_DIR}/vendor/json11.cpp
)

list(APPEND LIBWB_TEST_FILES
    ${THESE_TEST_FILES}
)

if (BUILD_LIBWB_LIBRARY)
  cuda_add_library(${WBLIB} ${LIBWB_SOURCE_FILES} STATIC)
  set_property(TARGET ${WBLIB} PROPERTY CXX_STANDARD 11)
endif (BUILD_LIBWB_LIBRARY)
