
file(GLOB WBHDR ${CMAKE_CURRENT_LIST_DIR}/*.hpp ${CMAKE_CURRENT_LIST_DIR}/*.h)
file(GLOB WBSRC ${CMAKE_CURRENT_LIST_DIR}/*.cpp ${CMAKE_CURRENT_LIST_DIR}/*.c)

if (BUILD_LIBWB_LIBRARY)
  cuda_add_library(${WBLIB} ${WBSRC} SHARED)
endif (BUILD_LIBWB_LIBRARY)
